disabled_rules:
  - blanket_disable_command
  - empty_enum_arguments
  - multiple_closures_with_trailing_closure
  - nesting
  - no_grouping_extension
  - switch_case_on_newline
  - unused_closure_parameter
opt_in_rules:
  - closure_body_length
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_literal_brackets
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition
analyzer_rules:
  - unused_declaration
  - unused_import
excluded:
  - Build
  - Carthage
  - DerivedData
  - Pods
closing_brace:
  severity: error
closure_parameter_position:
  severity: error
collection_alignment:
  severity: error
colon:
  severity: error
comma:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  warning: 6
  error: 8
deployment_target:
  severity: error
discouraged_object_literal:
  severity: error
empty_collection_literal:
  severity: error
empty_count:
  severity: warning
empty_parameters:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
empty_string:
  severity: error
explicit_init:
  severity: error
file_length:
  warning: 400
  error: 500
file_name_no_space:
  severity: error
first_where:
  severity: warning
flatmap_over_map_reduce:
  severity: error
for_where:
  severity: error
force_unwrapping:
  severity: error
  excluded: ".*Tests\\.swift"
function_body_length:
  warning: 30
  error: 40
function_parameter_count:
  warning: 3
  error: 8
identifier_name:
  min_length: 2
  max_length: 50
implicit_getter:
  severity: error
implicit_return:
  severity: warning
indentation_width:
  include_comments: false
  severity: error
is_disjoint:
  severity: error
joined_default_parameter:
  severity: error
large_tuple:
  warning: 4
  error: 6
last_where:
  severity: error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_hashing:
  severity: error
legacy_multiple:
  severity: error
legacy_nsgeometry_functions:
  severity: error
legacy_random:
  severity: error
line_length:
  warning: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
literal_expression_end_indentation:
  severity: error
lower_acl_than_parent:
  severity: warning
mark:
  severity: error
modifier_order:
  severity: error
multiline_literal_brackets:
  severity: error
no_space_in_method_call:
  severity: error
opening_brace:
  severity: error
operator_usage_whitespace:
  severity: error
operator_whitespace:
  severity: error
orphaned_doc_comment:
  severity: error
overridden_super_call:
  severity: error
pattern_matching_keywords:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
private_over_fileprivate:
  severity: error
prohibited_super_call:
  severity: error
protocol_property_accessors_order:
  severity: error
reduce_boolean:
  severity: error
redundant_discardable_let:
  severity: error
redundant_nil_coalescing:
  severity: warning
redundant_objc_attribute:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_set_access_control:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_type_annotation:
  severity: warning
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
shorthand_operator:
  severity: error
sorted_first_last:
  severity: error
statement_position:
  severity: error
strong_iboutlet:
  severity: error
switch_case_alignment:
  severity: error
syntactic_sugar:
  severity: error
toggle_bool:
  severity: error
trailing_closure:
  severity: warning
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_name:
  max_length: 50
unneeded_break_in_switch:
  severity: error
unneeded_parentheses_in_closure_argument:
  severity: error
unused_control_flow_label:
  severity: error
unused_enumerated:
  severity: error
unused_import:
  severity: error
unused_optional_binding:
  severity: error
unused_setter_value:
  severity: error
valid_ibinspectable:
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
vertical_whitespace:
  severity: error
vertical_whitespace_closing_braces:
  severity: error
vertical_whitespace_opening_braces:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
xct_specific_matcher:
  severity: error
yoda_condition:
  severity: error
