platform :ios, '17.0'

inhibit_all_warnings!

target 'TaskWise' do
  use_frameworks!

  pod 'Resolver'
  pod 'SwiftGen'
  pod 'SwiftLint'
end

target 'TaskWiseTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
